version: 2.1

orbs:
  android-sdk: rakutentech/android-sdk@0.2.1

workflows:
  build_and_test:
    jobs:
      - android-sdk/build:
          gradle-cache-key: >-
            gradle-
            {{ checksum "build.gradle" }}
            {{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            {{ checksum "signatureverifier/build.gradle" }}
          sdk-path: signatureverifier
          sample-app-path: sample
          filters:
            tags:
              only: /^v.*/
            branches:
              only: /.*/
